# Generated by Django 5.1 on 2024-10-03 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=150)),
                ('firstname', models.CharField(max_length=150)),
                ('middlename', models.CharField(blank=True, max_length=150, null=True)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
