# Generated by Django 5.1 on 2024-10-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gpsdata_gunshot_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsdata',
            name='gunshot_count',
            field=models.IntegerField(),
        ),
    ]
